accounts:
  - name: alice
    coins: ["20000z", "200000000stake"]
  - name: bob
    coins: ["10000z", "100000000stake"]
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuejs:
    path: "vue"
faucet:
  name: bob
  coins: ["5z", "100000stake"]
genesis:
  chain_id: "z-blockchain-1"
  consensus_params:
    block:
      time_iota_ms: "200"
      max_bytes: "22020096"
      max_gas: "-1"
  app_state:
    utxo:
      params:
        block_reward: "50000000000000000"
        halving_interval: 210000000
        min_difficulty: 1000000
        max_difficulty: 1000000000000
        hardware_acceleration: true
        supported_devices: ["nvidia-a100", "nvidia-h100", "xilinx-fpga"]
validators:
  - name: alice
    bonded: "100000000stake"