accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuejs:
    path: "vue"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "z-blockchain-1"
validators:
  - name: alice
    bonded: "100000000stake"
    home: "$HOME/.z-blockchain"